FROM cypress/included:14.1.0

WORKDIR /e2e

COPY package*.json ./

COPY run-suite.sh /e2e/run-suite.sh

ENTRYPOINT ["/bin/bash", "-c", "chmod +x /e2e/run-suite.sh && npm install && exec \"$@\"", "--"]

CMD ["./run-suite.sh"]

